# HTTP: allow GET, deny POST
acl get_method method GET
acl post_method method POST

#acl allowed_post_domains dstdomain example.com api.example.org
acl allowed_post_domains dstdomain example.com httpbin.org

http_access allow post_method allowed_post_domains
http_access deny post_method
http_access allow get_method
