# Listen only inside the shared namespace
port=53
listen-address=127.0.0.1

# Logging while debugging
log-queries
log-facility=-

# Cache
cache-size=1000

## Don't use /etc/resolv.conf
no-resolv
filter-AAAA
#domain-needed
#bogus-priv

# Upstream resolvers
#server=127.0.0.11
#server=1.0.0.1

# squid must be resolved for http/https
server=/proxy/127.0.0.11
nftset=/proxy/inet#filter#proxy_ip

# allow list: populate nftables sets with all resolved ips
server=/google.ch/127.0.0.11
#nftset=/google.ch/inet#filter#allow_dst
nftset=/#/inet#filter#allow_dst

# Optional: block some domains outright
#address=/#/
