# SPDX-FileCopyrightText: 2026 Alain Lehmann
#
# SPDX-License-Identifier: MIT

services:
  firewall:
    environment:
      TCP_ALLOWED_HOSTS: asdf.com
  proxy:
    environment:
      HTTP_DENY_ALL: google.ch
      #HTTP_ALLOW_ALL: httpbin.org
      HTTP_SAFE_METHODS: get
  sandbox:
    environment:
      UID: ${UID}
      GID: ${GID}
        #MODE: nix-develop:default
    working_dir: /project
    volumes:
      - ${PROJECT_ROOT:-$PWD}:/project
    command: >
      sh -c "
        nslookup asdf.com > /dev/null && echo OK || echo BAD should work
        nslookup github.com > /dev/null && echo BAD should fail || echo OK
        echo '------------------- should succeed---------------------'
        curl --fail --silent https://httpbin.org/get || (echo 'ERROR should not fail'; exit 1)
        echo '------------------- should succeed---------------------'
        curl --fail --silent http://httpbin.org/get || (echo 'ERROR should not fail'; exit 2)
        wait
        echo '------------------- should fail -----------------------'
        curl --fail --silent https://httpbin.org/post -d 'asdf' && exit 3 || echo 'expected to fail'
        echo '------------------- should fail -----------------------'
        curl --fail --silent http://httpbin.org/post -d 'asdf' && exit 4 || echo 'expected to fail'
        wait
      "
