# SPDX-FileCopyrightText: 2026 Alain Lehmann
#
# SPDX-License-Identifier: MIT

FROM debian:bookworm

RUN apt-get update && \
    apt-get install -y dnsmasq nftables iproute2 dnsutils

RUN cat <<'EOF' > /nftables.conf
define HOSTGATEWAY = @HOSTGATEWAY@
table ip localhost_ports_nat {
    set localhost_ports {
        type inet_service
        # elements = { port1, port2, etc }
    }
    chain output {
        type nat hook output priority -100;
        ip daddr 127.0.0.1 tcp dport @localhost_ports counter \
           dnat to $HOSTGATEWAY
    }
    chain postrouting {
        type nat hook postrouting priority 100;
        ip daddr $HOSTGATEWAY tcp dport @localhost_ports counter \
           masquerade
    }
}

table inet filter {

    set allow_dst {
        type ipv4_addr
        timeout 15m
    }
    set proxy_ip {
        type ipv4_addr
    }

    chain output {
        type filter hook output priority 0;
        policy drop;

        # existing connections
        ct state established,related accept

        # loopback
        oifname "lo" accept

        # Docker DNS resolvers
        ip daddr 127.0.0.11 udp dport 53 accept
        ip daddr 127.0.0.11 tcp dport 53 accept

        # Proxy: handle all http/https traffic
        ip daddr @proxy_ip tcp dport 3128 counter accept

        # Allowed destinations from dnsmasq for selected domains
        ip daddr @allow_dst counter accept
    }

    chain input {
        type filter hook input priority 0;
        policy drop;

        ct state established,related accept
        iifname "lo" accept
    }
}
EOF


RUN cat <<'EOF' > /etc/dnsmasq.conf
# Listen only inside the shared namespace
port=53
listen-address=127.0.0.1

# Logging while debugging
log-queries
log-facility=-

# Cache
cache-size=1000

## Don't use /etc/resolv.conf
no-resolv
filter-AAAA

# squid must be resolved for http/https
server=/proxy/127.0.0.11
nftset=/proxy/inet#filter#proxy_ip

# allow list: populate nftables sets with all resolved ips
nftset=/#/inet#filter#allow_dst
EOF

RUN cat <<'EOF' > /entrypoint.sh \
    && chmod +x /entrypoint.sh
#!/usr/bin/env bash
set -eu

echo "### inspect network namespace"
ip addr
nft list ruleset

echo "### network namespace hardening"
HOSTGATEWAY=$(getent hosts host.docker.internal | awk '{print $1}')
echo "HOSTGATEWAY=$HOSTGATEWAY"
sed -e "s/@HOSTGATEWAY@/$HOSTGATEWAY/g" /nftables.conf | nft -f -

nft flush set ip localhost_ports_nat localhost_ports
if [ -n "${LOCALHOST_PORTS:-}" ]; then
    nft add element ip localhost_ports_nat localhost_ports "{ $LOCALHOST_PORTS }"
fi

echo "### inspect network namespace"
nft list ruleset

echo "### generate tcp_allowed rules"
for host in ${TCP_ALLOWED_HOSTS:-}; do
  echo "server=/$host/127.0.0.11"
done >/etc/dnsmasq.tcp_allowed.conf

exec dnsmasq -k \
    --conf-file=/etc/dnsmasq.conf \
    --conf-file=/etc/dnsmasq.tcp_allowed.conf

EOF

ENTRYPOINT [ "/entrypoint.sh" ]

CMD ["dnsmasq", "-k", "--log-facility=-"]
