services:
  dns-fw:
    environment:
      TCP_ALLOWED_HOSTS: asdf.com
  proxy:
    environment:
      #HTTP_ALLOW_ALL: httpbin.org
      #HTTP_DENY_ALL: httpbin.org
      HTTP_SAFE_METHODS: get post
  sandbox:
    environment:
      UID: 501
      GID: 20
    working_dir: /project
    volumes:
      - ../:/project
    command: >
      sh -c "
        echo '------------------- should succeed---------------------'
        curl --fail --silent https://httpbin.org/get || (echo 'ERROR should not fail'; exit 1)
        echo '------------------- should succeed---------------------'
        curl --fail --silent http://httpbin.org/get || (echo 'ERROR should not fail'; exit 2)
        wait
        echo '------------------- should fail -----------------------'
        curl --fail --silent https://httpbin.org/post -d 'asdf' && exit 3 || echo 'expected to fail'
        echo '------------------- should fail -----------------------'
        curl --fail --silent http://httpbin.org/post -d 'asdf' && exit 4 || echo 'expected to fail'
        wait
      "
