# SPDX-FileCopyrightText: 2026 Alain Lehmann
#
# SPDX-License-Identifier: MIT

services:
  firewall:
    build:
      dockerfile: Dockerfile.dnsmasq
    networks: [int]
    cap_add: [NET_ADMIN]
    sysctls:
      net.ipv6.conf.all.disable_ipv6: "1"
    healthcheck:
      test: ["CMD-SHELL", "nslookup proxy 127.0.0.1 >/dev/null"]
      interval: 30s
      timeout: 2s
      retries: 5
      start_period: 10s
      start_interval: 0.5s

  proxy:
    build:
      dockerfile: Dockerfile.mitmproxy
    networks: [int]
    volumes:
      - fakeRootCA:/fakeRootCA:rw
    environment:
      RULE_FILES: "/mitm.rules.py"
      WEB_PASSWORD: password
    ports:
      - 3128:3128
      - 8081:8081
    healthcheck:
      test: ["CMD", "python", "-c", "import socket;socket.create_connection(('127.0.0.1',3128),2).close()"]
      interval: 30s
      timeout: 2s
      retries: 5
      start_period: 10s
      start_interval: 0.5s

  sandbox:
    build:
      dockerfile: Dockerfile.docker-devshell
    network_mode: service:firewall
    environment:
      NAMESERVER: 127.0.0.1 #dnsmasq
      HTTP_PROXY: http://proxy:3128
      HTTPS_PROXY: http://proxy:3128
      http_proxy: http://proxy:3128
      https_proxy: http://proxy:3128
      HOME: ${HOME:-/home/me}
    volumes:
      - nixStore:/nix
      - homeVolume:${HOME:-/home/me}
      - type: volume
        source: fakeRootCA
        target: /usr/local/share/ca-certificates
        volume:
          nocopy: true
    depends_on: # docker compose run automatically starts/stops dependent services
      firewall:
        condition: service_healthy
      proxy:
        condition: service_healthy
volumes:
  fakeRootCA:
  homeVolume:
  nixStore:

networks:
  int:
