# SPDX-FileCopyrightText: 2026 Alain Lehmann
#
# SPDX-License-Identifier: MIT

FROM alpine

RUN apk add --no-cache curl ca-certificates
RUN curl -sSfL https://artifacts.nixos.org/nix-installer \
			| sh -s -- install linux --init none --enable-flakes --no-confirm
ENV PATH=/nix/var/nix/profiles/default/bin:$PATH

RUN nix profile add \
        nixpkgs#direnv nixpkgs#nix-direnv nixpkgs#gosu nixpkgs#bashInteractive \
    && nix store gc

RUN cat <<'EOF' > /.direnvrc
: "${XDG_CACHE_HOME:="${HOME}/.cache"}"
declare -A direnv_layout_dirs
direnv_layout_dir() {
    local hash path
    echo "${direnv_layout_dirs[$PWD]:=$(
        hash="$(sha1sum - <<< "$PWD" | head -c40)"
        path="${PWD//[^a-zA-Z0-9]/-}"
        echo "${XDG_CACHE_HOME}/direnv/layouts/${hash}${path}"
    )}"
}
EOF

RUN cat <<'EOF' > /entrypoint.sh \
    && chmod +x /entrypoint.sh
#!/usr/bin/env sh

HOME=${HOME:-/home/me}
UID=${UID:-1000}
GID=${GID:-1000}
MODE=${MODE:-direnv}

case $MODE in
	direnv)
		EXECUTOR='direnv allow && exec direnv exec . "${@}"'
		;;
	nix-develop*)
		EXECUTOR='exec nix develop --no-warn-dirty "${MODE/nix-develop:/.#}" --command "${@}"'
		;;
	plain)
		EXECUTOR='exec "${@}"'
		;;
	*)
		echo "Unknown mode $MODE"
		exit 1
		;;
esac

ensure_store_permission() {
	owner=$(stat -c '%u:%g' /nix)
	if [ "$owner" != "$UID:$GID" ]; then
		echo "Fixing /nix ownership..."
		chown -R "$UID:$GID" /nix
	fi
}

ensure_home() {
	mkdir -p $HOME/.local/state/nix/profiles
	ln -fs /nix/var/nix/profiles/per-user/root/profile $HOME/.nix-profile
	mkdir -p $HOME/.config/direnv
	cp /.direnvrc $HOME/.config/direnv/direnvrc
	chown -R $UID:$GID $HOME
}

ensure_resolv_conf() {
	if [ -n "$NAMESERVER" ]; then
		echo "nameserver $NAMESERVER" > /etc/resolv.conf
	fi
}

as_user() {
	exec gosu $UID:$GID sh -c "
		export HOME=$HOME
		. /etc/profile.d/nix.sh;
		# workaround_macos_volume_mount_permission
		# - previous heuristic suggested 1s till permission okay
		# - waiting before user changes seems to not have an impact
		# - using ls on the folder seems to work too
		ls -lah . >/dev/null # workaround of macosFile permissinos
		$EXECUTOR
	" sh "$@"
}

update-ca-certificates
ensure_resolv_conf
ensure_home
ensure_store_permission
as_user "${@}"
EOF


ENTRYPOINT [ "/entrypoint.sh" ]
CMD [ "sh" ]
