# SPDX-FileCopyrightText: 2026 Alain Lehmann
#
# SPDX-License-Identifier: MIT

FROM mitmproxy/mitmproxy


RUN cat <<'EOF' > /entrypoint.sh \
    && chmod +x /entrypoint.sh
#!/usr/bin/env bash
set -eu

set -x;
export PYTHONUNBUFFERED=1

rm -f /fakeRootCA/mitmproxy-ca.crt
timeout 1 mitmdump --set confdir=/.mitmproxy || true;
cp /.mitmproxy/mitmproxy-ca-cert.pem /fakeRootCA/mitmproxy-ca.crt;

ARGS=(
    --listen-host 0.0.0.0
    --listen-port 3128
    --set confdir=/.mitmproxy
)

if [ -n "${WEB_PASSWORD:-}" ]; then
    ARGS+=(
        --web-host 0.0.0.0
        --web-port 8081
        --set "web_password=$WEB_PASSWORD"
    )
fi
for rule in ${RULE_FILES:-}; do
    ARGS+=(-s "$rule")
done

exec mitmweb "${ARGS[@]}"
EOF

RUN cat <<'EOF' > /mitm.rules.py
import os
import re
from mitmproxy import http, ctx


def env_set(name: str) -> set[str]:
    env_value = os.getenv(name, "").strip()
    env_value_split = re.split(r"[\s,]+", env_value)
    return {
        value.strip().lower()
        for value in env_value_split
        if value.strip()
    }

DENY = env_set("HTTP_DENY_ALL")
ALLOW = env_set("HTTP_ALLOW_ALL")
SAFE_METHODS = env_set("HTTP_SAFE_METHODS")

def matches(host: str, hosts: set[str]):
    return any(host == h or host.endswith("." + h) for h in hosts)

ctx.log.info(f"Allow all: {ALLOW}")
ctx.log.info(f"Deny all: {DENY}")
ctx.log.info(f"Default allowed method: {SAFE_METHODS}")

def request(flow: http.HTTPFlow):
    host = flow.request.pretty_host.lower()
    method = flow.request.method.lower()

    def deny():
        flow.response = http.Response.make(
            403,
            b"Blocked by proxy policy\n",
            {"Content-Type": "text/plain"},
        )

    if matches(host, DENY):
        deny()
    elif matches(host, ALLOW):
        return
    elif method not in SAFE_METHODS:
        deny()
EOF

ENTRYPOINT [ "/entrypoint.sh" ]
