services:
  dns-fw:
    build:
      dockerfile: Dockerfile.dnsmasq
    networks: [int]
    cap_add: [NET_ADMIN]
    sysctls:
      net.ipv6.conf.all.disable_ipv6: "1"
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf:ro
      - ./nftables.conf:/nftables.conf:ro
    healthcheck:
      test: ["CMD-SHELL", "nslookup proxy 127.0.0.1 >/dev/null"]
      interval: 30s
      timeout: 2s
      retries: 5
      start_period: 10s
      start_interval: 0.5s

  proxy:
    image: mitmproxy/mitmproxy
    networks: [int]
    command: |
      bash -c '
        set -x;
        export PYTHONUNBUFFERED=1
        rm -f /fakeRootCA/mitmproxy-ca.crt
        timeout 1 mitmdump --set confdir=/.mitmproxy || true;
        cp /.mitmproxy/mitmproxy-ca-cert.pem /fakeRootCA/mitmproxy-ca.crt;
        mitmweb --listen-host 0.0.0.0 --listen-port 3128 \
                --web-host 0.0.0.0 \
                --web-port 8081 \
                --set confdir=/.mitmproxy \
                --set web_password=password \
                -s /mitm.rules.py
      '
    volumes:
      - fakeRootCA:/fakeRootCA:rw
      - ./mitm.rules.py:/mitm.rules.py
    ports:
      - 3128:3128
      - 8081:8081
    healthcheck:
      test: ["CMD", "python", "-c", "import socket;socket.create_connection(('127.0.0.1',3128),2).close()"]
      interval: 30s
      timeout: 2s
      retries: 5
      start_period: 10s
      start_interval: 0.5s

  sandbox:
    build:
      context: ../docker-devshell
    network_mode: service:dns-fw
    environment:
      HTTP_PROXY: http://proxy:3128
      HTTPS_PROXY: http://proxy:3128
      http_proxy: http://proxy:3128
      https_proxy: http://proxy:3128
    volumes:
      - ./resolv.conf:/etc/resolv.conf:ro
      - nixStore:/nix
      - type: volume
        source: fakeRootCA
        target: /usr/local/share/ca-certificates
        volume:
          nocopy: true
      - $PWD/..:/project
    working_dir: /project
    depends_on: # docker compose run automatically starts/stops dependent services
      dns-fw:
        condition: service_healthy
      proxy:
        condition: service_healthy
volumes:
  fakeRootCA:

  nixStore:

networks:
  int:
