FROM debian:bookworm

RUN apt-get update && \
    apt-get install -y dnsmasq nftables iproute2 dnsutils

RUN cat <<'EOF' > /nftables.conf
table inet filter {

    set allow_dst {
        type ipv4_addr
    }
    set proxy_ip {
        type ipv4_addr
    }

    chain output {
        type filter hook output priority 0;
        policy drop;

        # existing connections
        ct state established,related accept

        # loopback
        oifname "lo" accept

        # DNS to upstream resolvers
        udp dport 53 accept
        tcp dport 53 accept

        # Proxy: handle all http/https traffic
        ip daddr @proxy_ip tcp dport 3128 counter accept

        # Allowed destinations from dnsmasq for selected domains
        ip daddr @allow_dst counter accept
    }

    chain input {
        type filter hook input priority 0;
        policy drop;

        ct state established,related accept
        iifname "lo" accept
    }
}
EOF


RUN cat <<'EOF' > /etc/dnsmasq.conf
# Listen only inside the shared namespace
port=53
listen-address=127.0.0.1

# Logging while debugging
log-queries
log-facility=-

# Cache
cache-size=1000

## Don't use /etc/resolv.conf
no-resolv
filter-AAAA

# squid must be resolved for http/https
server=/proxy/127.0.0.11
nftset=/proxy/inet#filter#proxy_ip

# allow list: populate nftables sets with all resolved ips
nftset=/#/inet#filter#allow_dst
EOF

RUN cat <<'EOF' > /entrypoint.sh \
    && chmod +x /entrypoint.sh
#!/usr/bin/env bash
set -eu

echo "network namespace hardening"
ip addr
nft list ruleset
nft -f /nftables.conf
nft list ruleset

echo "generate tcp_allowed rules"
for host in ${TCP_ALLOWED_HOSTS:-}; do
  echo "server=/$host/127.0.0.11"
done >/etc/dnsmasq.tcp_allowed.conf

exec dnsmasq -k \
    --conf-file=/etc/dnsmasq.conf \
    --conf-file=/etc/dnsmasq.tcp_allowed.conf

EOF

ENTRYPOINT [ "/entrypoint.sh" ]

CMD ["dnsmasq", "-k", "--log-facility=-"]
