services:
  dns-fw:
    build:
      dockerfile: Dockerfile.dnsmasq
    hostname: dns-fw
    cap_add:
      - NET_ADMIN
    sysctls:
      net.ipv6.conf.all.disable_ipv6: "1"
    command: >
      sh -c "
        set -eu
        ip addr
        nft list ruleset
        nft -f /nftables.conf
        nft list ruleset
        exec dnsmasq -k --conf-file=/etc/dnsmasq.conf
      "
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf:ro
      - ./nftables.conf:/nftables.conf:ro
    networks:
      - int
    healthcheck: 
      test: ["CMD-SHELL", "nslookup squid 127.0.0.1 >/dev/null"]
      interval: 30s
      timeout: 2s
      retries: 5
      start_period: 10s
      start_interval: 0.5s

  squid:
    build:
      dockerfile: Dockerfile.squid
    hostname: squid
    user: squid
    volumes:
      - ./squid.conf:/etc/squid/squid.conf:ro
      - fakeRootCA:/fakeRootCA:rw
    networks:
      - int
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 3128"]
      interval: 30s
      timeout: 2s
      retries: 5
      start_period: 10s
      start_interval: 0.5s

  sandbox:
    build:
      context: ../docker-devshell
    network_mode: service:dns-fw
    environment:
      HTTP_PROXY: http://squid:3128
      HTTPS_PROXY: http://squid:3128
      http_proxy: http://squid:3128
      https_proxy: http://squid:3128
    working_dir: /project
    volumes:
      - ../:/project
      - ./resolv.conf:/etc/resolv.conf:ro
      - nixStore:/nix
      - type: volume
        source: fakeRootCA
        target: /usr/local/share/ca-certificates
        volume:
          nocopy: true
    depends_on:
      dns-fw:
        condition: service_healthy
      squid:
        condition: service_healthy
    command: >
      sh -c "
        set -x
        echo '------------------- should succeed---------------------'
        curl --fail --silent https://httpbin.org/get || (echo 'ERROR should not fail'; exit 1)
        echo '------------------- should succeed---------------------'
        curl --fail --silent http://httpbin.org/get || (echo 'ERROR should not fail'; exit 2)
        wait
        echo '------------------- should fail -----------------------'
        curl --fail --silent https://httpbin.org/post -d 'asdf' && exit 3 || echo 'expected to fail'
        echo '------------------- should fail -----------------------'
        curl --fail --silent http://httpbin.org/post -d 'asdf' && exit 4 || echo 'expected to fail'
        wait
      "
volumes:
  fakeRootCA:

  nixStore:

networks:
  int:
