# SPDX-FileCopyrightText: 2026 Alain Lehmann
#
# SPDX-License-Identifier: MIT

services:
  firewall:
    environment:
      TCP_ALLOWED_HOSTS: asdf.com
      LOCALHOST_PORTS: 9991
  proxy:
    environment:
      HTTP_DENY_ALL: google.ch
      #HTTP_ALLOW_ALL: httpbingo.org
      HTTP_SAFE_METHODS: get
  hostservice1:
    image: traefik/whoami
    ports: [9991:80]
  hostservice2:
    image: traefik/whoami
    ports: [9992:80]
  sandbox:
    depends_on: [hostservice1, hostservice2]
    environment:
      MODE: plain
      #MODE: nix-develop:default
      UID: ${UID}
      GID: ${GID}
    command:
      - sh
      - -c
      - |
        failed=()

        final_report() {
          if (($${#failed[@]})); then
            printf '\nFailures:\n'
            printf '  %s\n' "$${failed[@]}"
            exit 1
          fi
        }

        check() {
          local expected=$$1
          shift

          "$$@" >/dev/null 2>&1
          local rc=$$?

          if [ "$$rc" -eq 0 ]; then
            actual=allow
          else
            actual=block
          fi

          if [ "$$actual" = "$$expected" ]; then
            color='\033[32m'
            status=PASS
          else
            color='\033[31m'
            status=FAIL
            failures+=($$*)
            failed+=("$$expected $$* (rc=$$rc, got $$actual)")
          fi


          printf "$${color}%-4s\033[0m (rc=%3d): expected %-7s %s\n" \
            "$$status" "$$rc" "$$expected" "$$*"

        }

        check allow nslookup asdf.com
        check block nslookup github.com

        check allow curl --fail --silent https://httpbingo.org/get
        check allow curl --fail --silent http://httpbingo.org/get
        check block curl --fail --silent https://httpbingo.org/post -d 'foo'
        check block curl --fail --silent http://httpbingo.org/post -d 'foo'
        check allow curl --fail --silent http://localhost:9991/hello
        check block curl --fail --silent http://localhost:9992/hello

        final_report
