FROM alpine:latest

RUN apk add -v --no-cache curl ca-certificates

RUN cat <<'EOF' > /entrypoint.sh \
 && chmod +x /entrypoint.sh
#!/bin/sh
set -e

echo "Starting container..."
update-ca-certificates

exec "$@"
EOF

ENTRYPOINT [ "/entrypoint.sh" ]
