table inet filter {

    set allow_dst {
        type ipv4_addr
    }
    set squid_ip {
        type ipv4_addr
    }

    chain output {
        type filter hook output priority 0;
        policy drop;

        # existing connections
        ct state established,related accept

        # loopback
        oifname "lo" accept


        # DNS to upstream resolvers
        udp dport 53 accept
        tcp dport 53 accept

        # Squid: handle all http/https traffic
        ip daddr @squid_ip tcp dport 3128 counter accept

        # Allowed destinations from dnsmasq for selected domains
        ip daddr @allow_dst tcp dport {80,443} counter accept
        ip daddr @allow_dst counter accept
    }

    chain input {
        type filter hook input priority 0;
        policy drop;

        ct state established,related accept
        iifname "lo" accept
    }
}
