#debug_options ALL,1 33,2 28,9
#debug_options ALL,9 33,9 28,9
access_log stdio:/dev/stdout

# =========================
# LISTENING PORT (REQUIRED)
# =========================
#http_port 3128 #no ssl-bump
http_port 3128 ssl-bump \
    cert=/etc/squid/certs/rootCA.crt \
    key=/etc/squid/certs/rootCA.key \
    generate-host-certificates=on

sslcrtd_program /usr/lib/squid/security_file_certgen \
    -s /var/lib/ssl_db -M 4MB
sslcrtd_children 5

# define ACLs
acl get_method method GET
acl post_method method POST
acl connect_method method CONNECT

# special hosts
acl allowed_nonssl_domains dstdomain localhost # .httpbin.org
acl allowed_ssl_domains ssl::server_name localhost #.httpbin.org

# ensure traffic is bumped for all but a selected set of sites
acl step1 at_step SslBump1
ssl_bump peek step1 # allow to peek at the domain, with MITM
ssl_bump splice allowed_ssl_domains
ssl_bump bump all

# block everything, but GET
http_access allow all connect_method
http_access allow all get_method
http_access allow allowed_nonssl_domains
http_access allow allowed_ssl_domains
http_access deny all # deny all non GET
